/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMyQuizzesRouteImport } from './routes/_authenticated/my-quizzes'
import { Route as AuthenticatedMyCompetenciesRouteImport } from './routes/_authenticated/my-competencies'
import { Route as AuthenticatedEvaluationsRouteImport } from './routes/_authenticated/evaluations'
import { Route as AuthenticatedDevelopmentPlansRouteImport } from './routes/_authenticated/development-plans'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedSupervisorIndexRouteImport } from './routes/_authenticated/supervisor/index'
import { Route as AuthenticatedSupervisorReportRouteImport } from './routes/_authenticated/supervisor/report'
import { Route as AuthenticatedSupervisorQuizzesRouteImport } from './routes/_authenticated/supervisor/quizzes'
import { Route as AuthenticatedSupervisorCompetenciesRouteImport } from './routes/_authenticated/supervisor/competencies'
import { Route as AuthenticatedReportsTeamRouteImport } from './routes/_authenticated/reports/team'
import { Route as AuthenticatedReportsIndividualRouteImport } from './routes/_authenticated/reports/individual'
import { Route as AuthenticatedMyQuizzesAssignmentIdRouteImport } from './routes/_authenticated/my-quizzes.$assignmentId'
import { Route as AuthenticatedHrOrganizationReportRouteImport } from './routes/_authenticated/hr/organization-report'
import { Route as AuthenticatedHrJobTitlesRouteImport } from './routes/_authenticated/hr/job-titles'
import { Route as AuthenticatedHrEmployeesRouteImport } from './routes/_authenticated/hr/employees'
import { Route as AuthenticatedHrCompetenciesReportRouteImport } from './routes/_authenticated/hr/competencies-report'
import { Route as AuthenticatedHrCompetenciesRouteImport } from './routes/_authenticated/hr/competencies'
import { Route as AuthenticatedEvaluationsNewRouteImport } from './routes/_authenticated/evaluations/new'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminQuizzesRouteImport } from './routes/_authenticated/admin/quizzes'
import { Route as AuthenticatedAdminJobTitlesRouteImport } from './routes/_authenticated/admin/job-titles'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin/employees'
import { Route as AuthenticatedAdminCompetenciesRouteImport } from './routes/_authenticated/admin/competencies'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedSupervisorQuizzesNewRouteImport } from './routes/_authenticated/supervisor/quizzes.new'
import { Route as AuthenticatedSupervisorEvaluateEmployeeIdRouteImport } from './routes/_authenticated/supervisor/evaluate.$employeeId'
import { Route as AuthenticatedSupervisorEmployeeEmployeeIdRouteImport } from './routes/_authenticated/supervisor/employee.$employeeId'
import { Route as AuthenticatedSupervisorPlanNewEmployeeIdRouteImport } from './routes/_authenticated/supervisor/plan.new.$employeeId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyQuizzesRoute = AuthenticatedMyQuizzesRouteImport.update({
  id: '/my-quizzes',
  path: '/my-quizzes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyCompetenciesRoute =
  AuthenticatedMyCompetenciesRouteImport.update({
    id: '/my-competencies',
    path: '/my-competencies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvaluationsRoute =
  AuthenticatedEvaluationsRouteImport.update({
    id: '/evaluations',
    path: '/evaluations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevelopmentPlansRoute =
  AuthenticatedDevelopmentPlansRouteImport.update({
    id: '/development-plans',
    path: '/development-plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupervisorIndexRoute =
  AuthenticatedSupervisorIndexRouteImport.update({
    id: '/supervisor/',
    path: '/supervisor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupervisorReportRoute =
  AuthenticatedSupervisorReportRouteImport.update({
    id: '/supervisor/report',
    path: '/supervisor/report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupervisorQuizzesRoute =
  AuthenticatedSupervisorQuizzesRouteImport.update({
    id: '/supervisor/quizzes',
    path: '/supervisor/quizzes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupervisorCompetenciesRoute =
  AuthenticatedSupervisorCompetenciesRouteImport.update({
    id: '/supervisor/competencies',
    path: '/supervisor/competencies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsTeamRoute =
  AuthenticatedReportsTeamRouteImport.update({
    id: '/reports/team',
    path: '/reports/team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndividualRoute =
  AuthenticatedReportsIndividualRouteImport.update({
    id: '/reports/individual',
    path: '/reports/individual',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyQuizzesAssignmentIdRoute =
  AuthenticatedMyQuizzesAssignmentIdRouteImport.update({
    id: '/$assignmentId',
    path: '/$assignmentId',
    getParentRoute: () => AuthenticatedMyQuizzesRoute,
  } as any)
const AuthenticatedHrOrganizationReportRoute =
  AuthenticatedHrOrganizationReportRouteImport.update({
    id: '/hr/organization-report',
    path: '/hr/organization-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrJobTitlesRoute =
  AuthenticatedHrJobTitlesRouteImport.update({
    id: '/hr/job-titles',
    path: '/hr/job-titles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrEmployeesRoute =
  AuthenticatedHrEmployeesRouteImport.update({
    id: '/hr/employees',
    path: '/hr/employees',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrCompetenciesReportRoute =
  AuthenticatedHrCompetenciesReportRouteImport.update({
    id: '/hr/competencies-report',
    path: '/hr/competencies-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrCompetenciesRoute =
  AuthenticatedHrCompetenciesRouteImport.update({
    id: '/hr/competencies',
    path: '/hr/competencies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvaluationsNewRoute =
  AuthenticatedEvaluationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedEvaluationsRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQuizzesRoute =
  AuthenticatedAdminQuizzesRouteImport.update({
    id: '/admin/quizzes',
    path: '/admin/quizzes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminJobTitlesRoute =
  AuthenticatedAdminJobTitlesRouteImport.update({
    id: '/admin/job-titles',
    path: '/admin/job-titles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/admin/employees',
    path: '/admin/employees',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCompetenciesRoute =
  AuthenticatedAdminCompetenciesRouteImport.update({
    id: '/admin/competencies',
    path: '/admin/competencies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupervisorQuizzesNewRoute =
  AuthenticatedSupervisorQuizzesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSupervisorQuizzesRoute,
  } as any)
const AuthenticatedSupervisorEvaluateEmployeeIdRoute =
  AuthenticatedSupervisorEvaluateEmployeeIdRouteImport.update({
    id: '/supervisor/evaluate/$employeeId',
    path: '/supervisor/evaluate/$employeeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupervisorEmployeeEmployeeIdRoute =
  AuthenticatedSupervisorEmployeeEmployeeIdRouteImport.update({
    id: '/supervisor/employee/$employeeId',
    path: '/supervisor/employee/$employeeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupervisorPlanNewEmployeeIdRoute =
  AuthenticatedSupervisorPlanNewEmployeeIdRouteImport.update({
    id: '/supervisor/plan/new/$employeeId',
    path: '/supervisor/plan/new/$employeeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/development-plans': typeof AuthenticatedDevelopmentPlansRoute
  '/evaluations': typeof AuthenticatedEvaluationsRouteWithChildren
  '/my-competencies': typeof AuthenticatedMyCompetenciesRoute
  '/my-quizzes': typeof AuthenticatedMyQuizzesRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/competencies': typeof AuthenticatedAdminCompetenciesRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/job-titles': typeof AuthenticatedAdminJobTitlesRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/evaluations/new': typeof AuthenticatedEvaluationsNewRoute
  '/hr/competencies': typeof AuthenticatedHrCompetenciesRoute
  '/hr/competencies-report': typeof AuthenticatedHrCompetenciesReportRoute
  '/hr/employees': typeof AuthenticatedHrEmployeesRoute
  '/hr/job-titles': typeof AuthenticatedHrJobTitlesRoute
  '/hr/organization-report': typeof AuthenticatedHrOrganizationReportRoute
  '/my-quizzes/$assignmentId': typeof AuthenticatedMyQuizzesAssignmentIdRoute
  '/reports/individual': typeof AuthenticatedReportsIndividualRoute
  '/reports/team': typeof AuthenticatedReportsTeamRoute
  '/supervisor/competencies': typeof AuthenticatedSupervisorCompetenciesRoute
  '/supervisor/quizzes': typeof AuthenticatedSupervisorQuizzesRouteWithChildren
  '/supervisor/report': typeof AuthenticatedSupervisorReportRoute
  '/supervisor/': typeof AuthenticatedSupervisorIndexRoute
  '/supervisor/employee/$employeeId': typeof AuthenticatedSupervisorEmployeeEmployeeIdRoute
  '/supervisor/evaluate/$employeeId': typeof AuthenticatedSupervisorEvaluateEmployeeIdRoute
  '/supervisor/quizzes/new': typeof AuthenticatedSupervisorQuizzesNewRoute
  '/supervisor/plan/new/$employeeId': typeof AuthenticatedSupervisorPlanNewEmployeeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/development-plans': typeof AuthenticatedDevelopmentPlansRoute
  '/evaluations': typeof AuthenticatedEvaluationsRouteWithChildren
  '/my-competencies': typeof AuthenticatedMyCompetenciesRoute
  '/my-quizzes': typeof AuthenticatedMyQuizzesRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/competencies': typeof AuthenticatedAdminCompetenciesRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/job-titles': typeof AuthenticatedAdminJobTitlesRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/evaluations/new': typeof AuthenticatedEvaluationsNewRoute
  '/hr/competencies': typeof AuthenticatedHrCompetenciesRoute
  '/hr/competencies-report': typeof AuthenticatedHrCompetenciesReportRoute
  '/hr/employees': typeof AuthenticatedHrEmployeesRoute
  '/hr/job-titles': typeof AuthenticatedHrJobTitlesRoute
  '/hr/organization-report': typeof AuthenticatedHrOrganizationReportRoute
  '/my-quizzes/$assignmentId': typeof AuthenticatedMyQuizzesAssignmentIdRoute
  '/reports/individual': typeof AuthenticatedReportsIndividualRoute
  '/reports/team': typeof AuthenticatedReportsTeamRoute
  '/supervisor/competencies': typeof AuthenticatedSupervisorCompetenciesRoute
  '/supervisor/quizzes': typeof AuthenticatedSupervisorQuizzesRouteWithChildren
  '/supervisor/report': typeof AuthenticatedSupervisorReportRoute
  '/supervisor': typeof AuthenticatedSupervisorIndexRoute
  '/supervisor/employee/$employeeId': typeof AuthenticatedSupervisorEmployeeEmployeeIdRoute
  '/supervisor/evaluate/$employeeId': typeof AuthenticatedSupervisorEvaluateEmployeeIdRoute
  '/supervisor/quizzes/new': typeof AuthenticatedSupervisorQuizzesNewRoute
  '/supervisor/plan/new/$employeeId': typeof AuthenticatedSupervisorPlanNewEmployeeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/development-plans': typeof AuthenticatedDevelopmentPlansRoute
  '/_authenticated/evaluations': typeof AuthenticatedEvaluationsRouteWithChildren
  '/_authenticated/my-competencies': typeof AuthenticatedMyCompetenciesRoute
  '/_authenticated/my-quizzes': typeof AuthenticatedMyQuizzesRouteWithChildren
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/competencies': typeof AuthenticatedAdminCompetenciesRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/_authenticated/admin/job-titles': typeof AuthenticatedAdminJobTitlesRoute
  '/_authenticated/admin/quizzes': typeof AuthenticatedAdminQuizzesRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/evaluations/new': typeof AuthenticatedEvaluationsNewRoute
  '/_authenticated/hr/competencies': typeof AuthenticatedHrCompetenciesRoute
  '/_authenticated/hr/competencies-report': typeof AuthenticatedHrCompetenciesReportRoute
  '/_authenticated/hr/employees': typeof AuthenticatedHrEmployeesRoute
  '/_authenticated/hr/job-titles': typeof AuthenticatedHrJobTitlesRoute
  '/_authenticated/hr/organization-report': typeof AuthenticatedHrOrganizationReportRoute
  '/_authenticated/my-quizzes/$assignmentId': typeof AuthenticatedMyQuizzesAssignmentIdRoute
  '/_authenticated/reports/individual': typeof AuthenticatedReportsIndividualRoute
  '/_authenticated/reports/team': typeof AuthenticatedReportsTeamRoute
  '/_authenticated/supervisor/competencies': typeof AuthenticatedSupervisorCompetenciesRoute
  '/_authenticated/supervisor/quizzes': typeof AuthenticatedSupervisorQuizzesRouteWithChildren
  '/_authenticated/supervisor/report': typeof AuthenticatedSupervisorReportRoute
  '/_authenticated/supervisor/': typeof AuthenticatedSupervisorIndexRoute
  '/_authenticated/supervisor/employee/$employeeId': typeof AuthenticatedSupervisorEmployeeEmployeeIdRoute
  '/_authenticated/supervisor/evaluate/$employeeId': typeof AuthenticatedSupervisorEvaluateEmployeeIdRoute
  '/_authenticated/supervisor/quizzes/new': typeof AuthenticatedSupervisorQuizzesNewRoute
  '/_authenticated/supervisor/plan/new/$employeeId': typeof AuthenticatedSupervisorPlanNewEmployeeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/change-password'
    | '/dashboard'
    | '/development-plans'
    | '/evaluations'
    | '/my-competencies'
    | '/my-quizzes'
    | '/admin/analytics'
    | '/admin/competencies'
    | '/admin/employees'
    | '/admin/job-titles'
    | '/admin/quizzes'
    | '/admin/reports'
    | '/admin/roles'
    | '/evaluations/new'
    | '/hr/competencies'
    | '/hr/competencies-report'
    | '/hr/employees'
    | '/hr/job-titles'
    | '/hr/organization-report'
    | '/my-quizzes/$assignmentId'
    | '/reports/individual'
    | '/reports/team'
    | '/supervisor/competencies'
    | '/supervisor/quizzes'
    | '/supervisor/report'
    | '/supervisor/'
    | '/supervisor/employee/$employeeId'
    | '/supervisor/evaluate/$employeeId'
    | '/supervisor/quizzes/new'
    | '/supervisor/plan/new/$employeeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/change-password'
    | '/dashboard'
    | '/development-plans'
    | '/evaluations'
    | '/my-competencies'
    | '/my-quizzes'
    | '/admin/analytics'
    | '/admin/competencies'
    | '/admin/employees'
    | '/admin/job-titles'
    | '/admin/quizzes'
    | '/admin/reports'
    | '/admin/roles'
    | '/evaluations/new'
    | '/hr/competencies'
    | '/hr/competencies-report'
    | '/hr/employees'
    | '/hr/job-titles'
    | '/hr/organization-report'
    | '/my-quizzes/$assignmentId'
    | '/reports/individual'
    | '/reports/team'
    | '/supervisor/competencies'
    | '/supervisor/quizzes'
    | '/supervisor/report'
    | '/supervisor'
    | '/supervisor/employee/$employeeId'
    | '/supervisor/evaluate/$employeeId'
    | '/supervisor/quizzes/new'
    | '/supervisor/plan/new/$employeeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/change-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/development-plans'
    | '/_authenticated/evaluations'
    | '/_authenticated/my-competencies'
    | '/_authenticated/my-quizzes'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/competencies'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/job-titles'
    | '/_authenticated/admin/quizzes'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/roles'
    | '/_authenticated/evaluations/new'
    | '/_authenticated/hr/competencies'
    | '/_authenticated/hr/competencies-report'
    | '/_authenticated/hr/employees'
    | '/_authenticated/hr/job-titles'
    | '/_authenticated/hr/organization-report'
    | '/_authenticated/my-quizzes/$assignmentId'
    | '/_authenticated/reports/individual'
    | '/_authenticated/reports/team'
    | '/_authenticated/supervisor/competencies'
    | '/_authenticated/supervisor/quizzes'
    | '/_authenticated/supervisor/report'
    | '/_authenticated/supervisor/'
    | '/_authenticated/supervisor/employee/$employeeId'
    | '/_authenticated/supervisor/evaluate/$employeeId'
    | '/_authenticated/supervisor/quizzes/new'
    | '/_authenticated/supervisor/plan/new/$employeeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-quizzes': {
      id: '/_authenticated/my-quizzes'
      path: '/my-quizzes'
      fullPath: '/my-quizzes'
      preLoaderRoute: typeof AuthenticatedMyQuizzesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-competencies': {
      id: '/_authenticated/my-competencies'
      path: '/my-competencies'
      fullPath: '/my-competencies'
      preLoaderRoute: typeof AuthenticatedMyCompetenciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evaluations': {
      id: '/_authenticated/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof AuthenticatedEvaluationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/development-plans': {
      id: '/_authenticated/development-plans'
      path: '/development-plans'
      fullPath: '/development-plans'
      preLoaderRoute: typeof AuthenticatedDevelopmentPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor/': {
      id: '/_authenticated/supervisor/'
      path: '/supervisor'
      fullPath: '/supervisor/'
      preLoaderRoute: typeof AuthenticatedSupervisorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor/report': {
      id: '/_authenticated/supervisor/report'
      path: '/supervisor/report'
      fullPath: '/supervisor/report'
      preLoaderRoute: typeof AuthenticatedSupervisorReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor/quizzes': {
      id: '/_authenticated/supervisor/quizzes'
      path: '/supervisor/quizzes'
      fullPath: '/supervisor/quizzes'
      preLoaderRoute: typeof AuthenticatedSupervisorQuizzesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor/competencies': {
      id: '/_authenticated/supervisor/competencies'
      path: '/supervisor/competencies'
      fullPath: '/supervisor/competencies'
      preLoaderRoute: typeof AuthenticatedSupervisorCompetenciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/team': {
      id: '/_authenticated/reports/team'
      path: '/reports/team'
      fullPath: '/reports/team'
      preLoaderRoute: typeof AuthenticatedReportsTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/individual': {
      id: '/_authenticated/reports/individual'
      path: '/reports/individual'
      fullPath: '/reports/individual'
      preLoaderRoute: typeof AuthenticatedReportsIndividualRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-quizzes/$assignmentId': {
      id: '/_authenticated/my-quizzes/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/my-quizzes/$assignmentId'
      preLoaderRoute: typeof AuthenticatedMyQuizzesAssignmentIdRouteImport
      parentRoute: typeof AuthenticatedMyQuizzesRoute
    }
    '/_authenticated/hr/organization-report': {
      id: '/_authenticated/hr/organization-report'
      path: '/hr/organization-report'
      fullPath: '/hr/organization-report'
      preLoaderRoute: typeof AuthenticatedHrOrganizationReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/job-titles': {
      id: '/_authenticated/hr/job-titles'
      path: '/hr/job-titles'
      fullPath: '/hr/job-titles'
      preLoaderRoute: typeof AuthenticatedHrJobTitlesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/employees': {
      id: '/_authenticated/hr/employees'
      path: '/hr/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof AuthenticatedHrEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/competencies-report': {
      id: '/_authenticated/hr/competencies-report'
      path: '/hr/competencies-report'
      fullPath: '/hr/competencies-report'
      preLoaderRoute: typeof AuthenticatedHrCompetenciesReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/competencies': {
      id: '/_authenticated/hr/competencies'
      path: '/hr/competencies'
      fullPath: '/hr/competencies'
      preLoaderRoute: typeof AuthenticatedHrCompetenciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evaluations/new': {
      id: '/_authenticated/evaluations/new'
      path: '/new'
      fullPath: '/evaluations/new'
      preLoaderRoute: typeof AuthenticatedEvaluationsNewRouteImport
      parentRoute: typeof AuthenticatedEvaluationsRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/quizzes': {
      id: '/_authenticated/admin/quizzes'
      path: '/admin/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/job-titles': {
      id: '/_authenticated/admin/job-titles'
      path: '/admin/job-titles'
      fullPath: '/admin/job-titles'
      preLoaderRoute: typeof AuthenticatedAdminJobTitlesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/competencies': {
      id: '/_authenticated/admin/competencies'
      path: '/admin/competencies'
      fullPath: '/admin/competencies'
      preLoaderRoute: typeof AuthenticatedAdminCompetenciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor/quizzes/new': {
      id: '/_authenticated/supervisor/quizzes/new'
      path: '/new'
      fullPath: '/supervisor/quizzes/new'
      preLoaderRoute: typeof AuthenticatedSupervisorQuizzesNewRouteImport
      parentRoute: typeof AuthenticatedSupervisorQuizzesRoute
    }
    '/_authenticated/supervisor/evaluate/$employeeId': {
      id: '/_authenticated/supervisor/evaluate/$employeeId'
      path: '/supervisor/evaluate/$employeeId'
      fullPath: '/supervisor/evaluate/$employeeId'
      preLoaderRoute: typeof AuthenticatedSupervisorEvaluateEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor/employee/$employeeId': {
      id: '/_authenticated/supervisor/employee/$employeeId'
      path: '/supervisor/employee/$employeeId'
      fullPath: '/supervisor/employee/$employeeId'
      preLoaderRoute: typeof AuthenticatedSupervisorEmployeeEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor/plan/new/$employeeId': {
      id: '/_authenticated/supervisor/plan/new/$employeeId'
      path: '/supervisor/plan/new/$employeeId'
      fullPath: '/supervisor/plan/new/$employeeId'
      preLoaderRoute: typeof AuthenticatedSupervisorPlanNewEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedEvaluationsRouteChildren {
  AuthenticatedEvaluationsNewRoute: typeof AuthenticatedEvaluationsNewRoute
}

const AuthenticatedEvaluationsRouteChildren: AuthenticatedEvaluationsRouteChildren =
  {
    AuthenticatedEvaluationsNewRoute: AuthenticatedEvaluationsNewRoute,
  }

const AuthenticatedEvaluationsRouteWithChildren =
  AuthenticatedEvaluationsRoute._addFileChildren(
    AuthenticatedEvaluationsRouteChildren,
  )

interface AuthenticatedMyQuizzesRouteChildren {
  AuthenticatedMyQuizzesAssignmentIdRoute: typeof AuthenticatedMyQuizzesAssignmentIdRoute
}

const AuthenticatedMyQuizzesRouteChildren: AuthenticatedMyQuizzesRouteChildren =
  {
    AuthenticatedMyQuizzesAssignmentIdRoute:
      AuthenticatedMyQuizzesAssignmentIdRoute,
  }

const AuthenticatedMyQuizzesRouteWithChildren =
  AuthenticatedMyQuizzesRoute._addFileChildren(
    AuthenticatedMyQuizzesRouteChildren,
  )

interface AuthenticatedSupervisorQuizzesRouteChildren {
  AuthenticatedSupervisorQuizzesNewRoute: typeof AuthenticatedSupervisorQuizzesNewRoute
}

const AuthenticatedSupervisorQuizzesRouteChildren: AuthenticatedSupervisorQuizzesRouteChildren =
  {
    AuthenticatedSupervisorQuizzesNewRoute:
      AuthenticatedSupervisorQuizzesNewRoute,
  }

const AuthenticatedSupervisorQuizzesRouteWithChildren =
  AuthenticatedSupervisorQuizzesRoute._addFileChildren(
    AuthenticatedSupervisorQuizzesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevelopmentPlansRoute: typeof AuthenticatedDevelopmentPlansRoute
  AuthenticatedEvaluationsRoute: typeof AuthenticatedEvaluationsRouteWithChildren
  AuthenticatedMyCompetenciesRoute: typeof AuthenticatedMyCompetenciesRoute
  AuthenticatedMyQuizzesRoute: typeof AuthenticatedMyQuizzesRouteWithChildren
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCompetenciesRoute: typeof AuthenticatedAdminCompetenciesRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRoute
  AuthenticatedAdminJobTitlesRoute: typeof AuthenticatedAdminJobTitlesRoute
  AuthenticatedAdminQuizzesRoute: typeof AuthenticatedAdminQuizzesRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedHrCompetenciesRoute: typeof AuthenticatedHrCompetenciesRoute
  AuthenticatedHrCompetenciesReportRoute: typeof AuthenticatedHrCompetenciesReportRoute
  AuthenticatedHrEmployeesRoute: typeof AuthenticatedHrEmployeesRoute
  AuthenticatedHrJobTitlesRoute: typeof AuthenticatedHrJobTitlesRoute
  AuthenticatedHrOrganizationReportRoute: typeof AuthenticatedHrOrganizationReportRoute
  AuthenticatedReportsIndividualRoute: typeof AuthenticatedReportsIndividualRoute
  AuthenticatedReportsTeamRoute: typeof AuthenticatedReportsTeamRoute
  AuthenticatedSupervisorCompetenciesRoute: typeof AuthenticatedSupervisorCompetenciesRoute
  AuthenticatedSupervisorQuizzesRoute: typeof AuthenticatedSupervisorQuizzesRouteWithChildren
  AuthenticatedSupervisorReportRoute: typeof AuthenticatedSupervisorReportRoute
  AuthenticatedSupervisorIndexRoute: typeof AuthenticatedSupervisorIndexRoute
  AuthenticatedSupervisorEmployeeEmployeeIdRoute: typeof AuthenticatedSupervisorEmployeeEmployeeIdRoute
  AuthenticatedSupervisorEvaluateEmployeeIdRoute: typeof AuthenticatedSupervisorEvaluateEmployeeIdRoute
  AuthenticatedSupervisorPlanNewEmployeeIdRoute: typeof AuthenticatedSupervisorPlanNewEmployeeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevelopmentPlansRoute: AuthenticatedDevelopmentPlansRoute,
  AuthenticatedEvaluationsRoute: AuthenticatedEvaluationsRouteWithChildren,
  AuthenticatedMyCompetenciesRoute: AuthenticatedMyCompetenciesRoute,
  AuthenticatedMyQuizzesRoute: AuthenticatedMyQuizzesRouteWithChildren,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminCompetenciesRoute: AuthenticatedAdminCompetenciesRoute,
  AuthenticatedAdminEmployeesRoute: AuthenticatedAdminEmployeesRoute,
  AuthenticatedAdminJobTitlesRoute: AuthenticatedAdminJobTitlesRoute,
  AuthenticatedAdminQuizzesRoute: AuthenticatedAdminQuizzesRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedHrCompetenciesRoute: AuthenticatedHrCompetenciesRoute,
  AuthenticatedHrCompetenciesReportRoute:
    AuthenticatedHrCompetenciesReportRoute,
  AuthenticatedHrEmployeesRoute: AuthenticatedHrEmployeesRoute,
  AuthenticatedHrJobTitlesRoute: AuthenticatedHrJobTitlesRoute,
  AuthenticatedHrOrganizationReportRoute:
    AuthenticatedHrOrganizationReportRoute,
  AuthenticatedReportsIndividualRoute: AuthenticatedReportsIndividualRoute,
  AuthenticatedReportsTeamRoute: AuthenticatedReportsTeamRoute,
  AuthenticatedSupervisorCompetenciesRoute:
    AuthenticatedSupervisorCompetenciesRoute,
  AuthenticatedSupervisorQuizzesRoute:
    AuthenticatedSupervisorQuizzesRouteWithChildren,
  AuthenticatedSupervisorReportRoute: AuthenticatedSupervisorReportRoute,
  AuthenticatedSupervisorIndexRoute: AuthenticatedSupervisorIndexRoute,
  AuthenticatedSupervisorEmployeeEmployeeIdRoute:
    AuthenticatedSupervisorEmployeeEmployeeIdRoute,
  AuthenticatedSupervisorEvaluateEmployeeIdRoute:
    AuthenticatedSupervisorEvaluateEmployeeIdRoute,
  AuthenticatedSupervisorPlanNewEmployeeIdRoute:
    AuthenticatedSupervisorPlanNewEmployeeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
